name       : haskell-hspec-smallcheck
version    : 0.5.2
release    : 3
source     :
    - https://hackage.haskell.org/package/hspec-smallcheck-0.5.2/hspec-smallcheck-0.5.2.tar.gz : 9a301a26a439a92b303217545b65792bd8500f25aeccbe48e46dfe914ef58119
license    : MIT
component  : programming.haskell
summary    : SmallCheck support for the Hspec testing framework
description: |
    SmallCheck support for the Hspec testing framework
builddeps  :
    - haskell-cabal-install
    - haskell-hspec-core-devel
    - haskell-setenv-devel
    - haskell-smallcheck-devel
rundeps    :
    - devel:
        - haskell-hspec-core-devel
        - haskell-setenv-devel
        - haskell-smallcheck-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
