name       : haskell-hspec-smallcheck
version    : 0.4.2
release    : 1
source     :
    - http://hackage.haskell.org/package/hspec-smallcheck-0.4.2/hspec-smallcheck-0.4.2.tar.gz : ba09d4b2eb1c6ff2d680aa09b36eb6c0b395cc258ae716b8d1db511073385ed3
license    : MIT
component  : programming.haskell
summary    : SmallCheck support for the Hspec testing framework 
description: |
    SmallCheck support for the Hspec testing framework 
builddeps  :
    - haskell-cabal-install
    - haskell-hspec-core
    - haskell-smallcheck
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
